package com.alethicode.dto.response;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * 学生侧画像 dashboard 响应（GET /api/ai/tutor/profile/me）。
 *
 * 设计文档：docs/plans/2026-04-25-persistent-memory-layer-design.md §6.5.1
 *
 * 脱敏规则（设计 §6.2.4）：
 * - 不暴露 detector_name 等内部检测器名
 * - 不暴露 misconception_distribution raw 数据
 * - 仅返回当前学生自己的画像
 */
public record StudentProfileView(
        Long userId,
        boolean personalizationEnabled,
        boolean isUserOverridden,
        NarrativeSummaryView narrativeSummary,
        LearningStyleView learningStyle,
        List<KcView> topWeakKcs,
        List<KcView> topStrongKcs,
        List<ErrorPatternView> topErrors,
        Map<String, Object> stats30d
) {
    public record NarrativeSummaryView(
            int version,
            String text,
            Instant updatedAt,
            boolean autoGenerated
    ) {}

    public record LearningStyleView(
            String key,
            String label
    ) {}

    public record KcView(
            String name,
            double mastery
    ) {}

    public record ErrorPatternView(
            String taxonomyLabel,
            int count30d,
            String lastSeen
    ) {}
}
