services:
  frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl-frontend-rendered.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
