import { ref } from 'vue'
import api from '@oj/api'

/**
 * 封装学习者画像 API 状态；调用方各自实例化，避免引入全局状态。
 */
export function useProfileApi() {
  const profile = ref(null)
  const loading = ref(false)
  const saving = ref(false)
  const error = ref('')

  async function load() {
    loading.value = true
    error.value = ''
    try {
      const res = await api.getMyProfile()
      profile.value = normalizeProfilePayload(unwrap(res))
    } catch (err) {
      error.value = describe(err)
    } finally {
      loading.value = false
    }
  }

  async function refresh() {
    saving.value = true
    error.value = ''
    try {
      await api.refreshProfileSummary()
      await load()
    } catch (err) {
      error.value = describe(err)
    } finally {
      saving.value = false
    }
  }

  async function updatePreferences(enabled) {
    saving.value = true
    error.value = ''
    try {
      await api.updateProfilePreferences(enabled)
      if (profile.value) {
        profile.value = { ...profile.value, personalizationEnabled: enabled }
      }
    } catch (err) {
      error.value = describe(err)
    } finally {
      saving.value = false
    }
  }

  async function overrideSummary(text) {
    saving.value = true
    error.value = ''
    try {
      await api.overrideProfileSummary(text)
      await load()
    } catch (err) {
      error.value = describe(err)
    } finally {
      saving.value = false
    }
  }

  return {
    profile,
    loading,
    saving,
    error,
    load,
    refresh,
    updatePreferences,
    overrideSummary
  }
}

function normalizeProfilePayload(raw) {
  if (!raw || typeof raw !== 'object') return raw
  return {
    ...raw,
    personalizationEnabled: raw.personalization_enabled !== false && raw.personalizationEnabled !== false,
    isUserOverridden: Boolean(raw.is_user_overridden || raw.isUserOverridden),
    narrativeSummary: raw.narrative_summary || raw.narrativeSummary || {
      version: 0,
      text: '',
      updatedAt: '',
      autoGenerated: true
    },
    learningStyle: raw.learning_style || raw.learningStyle || {
      key: 'step_by_step',
      label: '逐步引导'
    },
    topWeakKcs: raw.top_weak_kcs || raw.topWeakKcs || [],
    topStrongKcs: raw.top_strong_kcs || raw.topStrongKcs || [],
    topErrors: normalizeTopErrors(raw.top_errors || raw.topErrors || []),
    stats30d: raw.stats_30d || raw.stats30d || {}
  }
}

function normalizeTopErrors(errors) {
  if (!Array.isArray(errors)) return []
  return errors.map(item => ({
    ...item,
    taxonomyLabel: item.taxonomy_label || item.taxonomyLabel || '',
    count30d: item.count_30d || item.count30d || 0,
    lastSeen: item.last_seen || item.lastSeen || ''
  }))
}

function unwrap(res) {
  if (!res) return null
  if (res.data && Object.prototype.hasOwnProperty.call(res.data, 'data')) {
    return res.data.data
  }
  return res.data
}

function describe(err) {
  if (!err) return 'unknown error'
  if (err.message) return err.message
  if (err.data && err.data.data) return String(err.data.data)
  return 'request failed'
}
