apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: alethicode-prometheus
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
